fail_fast: false
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.3
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.150
    hooks:
      - id: ruff
        args: [--config, pyproject.toml, --fix]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline", "force-use-all-plugins"]
        exclude: .*\.lock*|.*\.md|.*\.ipynb|.secrets.baseline|.*\.svg|.*\.pkl|.*\.drawio
